# Generated by Django 3.1.7 on 2022-01-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Творець',
                'verbose_name_plural': 'Творці',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sell.creator')),
            ],
            options={
                'verbose_name': 'Покликання',
                'verbose_name_plural': 'Покликання',
            },
        ),
        migrations.RemoveField(
            model_name='links',
            name='creator',
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sell.link')),
                ('card_number', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=5)),
                ('csv', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Creators',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
