# Generated by Django 3.1.7 on 2022-02-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_auto_20220131_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='Empty', max_length=20),
        ),
    ]
