# Generated by Django 3.1.7 on 2022-02-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0005_auto_20220209_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id',
            new_name='link_id',
        ),
    ]
