# Generated by Django 3.1.7 on 2022-02-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0008_auto_20220212_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_number',
            new_name='cardnumber',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='date',
            new_name='expirationdate',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='csv',
            new_name='securitycode',
        ),
    ]
