# Generated by Django 3.1.7 on 2022-02-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0009_auto_20220212_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='teleid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
