# Generated by Django 3.1.7 on 2022-04-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0010_creator_teleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='money',
            field=models.IntegerField(blank=True, default=3300, null=True),
        ),
    ]
