# Generated by Django 3.1.7 on 2022-05-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0011_link_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expirationdate',
            field=models.CharField(max_length=7),
        ),
    ]
